let drillYear = null, editingId = null, candidates = [];
const api = async (path, method = 'GET', payload) => {
  const res = await fetch(path, { method, headers: payload instanceof File ? {} : { 'Content-Type': 'application/json' }, body: payload instanceof File ? payload : payload === undefined ? undefined : JSON.stringify(payload) });
  const value = await res.json(); if (!res.ok) throw Error(value.error || 'บันทึกไม่สำเร็จ'); return value;
};
function toast(message, error = false) { const el = $('message'); el.textContent = message; el.style.color = error ? '#a33838' : '#185d42'; clearTimeout(toast.timer); toast.timer = setTimeout(() => el.textContent = '', 6000) }
function syncYears() { const from = $('from').value, to = $('to').value; const ys = [...new Set(data.map(x => x.year))].sort((a, b) => a - b); $('from').innerHTML = ys.map(y => `<option value="${y}">${y + 543}</option>`).join(''); $('to').innerHTML = $('from').innerHTML; $('from').value = ys.includes(+from) ? from : String(ys[0]); $('to').value = ys.includes(+to) ? to : String(ys.at(-1)) }
async function refresh() { data = await api('/api/publications'); staff = [...new Set([...data.map(x => x.staff), ...Object.keys(mapping)])].sort(); selected = new Set(staff); syncYears(); options(); programEditor(); $('staffNames').innerHTML = staff.map(x => `<option value="${escapeHTML(x)}"></option>`).join(''); page = 0; render() }
function clearForm() { editingId = null; $('pubForm').reset(); $('pubYear').value = new Date().getFullYear(); $('pubMonth').value = new Date().getMonth() + 1; $('pubSave').textContent = 'เพิ่มผลงาน'; $('pubCancel').hidden = true }
function fillForm(id) { const row = data.find(x => x.id === id); if (!row) return; $('manage').open = true; editingId = id; $('pubStaff').value = row.staff; $('pubDetail').value = row.detail; $('pubType').value = row.type; $('pubYear').value = row.year; $('pubMonth').value = row.month; $('pubIndexing').value = row.indexing === 'ไม่ระบุ' ? '' : row.indexing; $('pubAffiliation').value = row.affiliation; $('pubSave').textContent = 'บันทึกการแก้ไข'; $('pubCancel').hidden = false; $('editor').scrollIntoView({ behavior: 'smooth', block: 'start' }) }
function formValue() { return { staff: $('pubStaff').value, detail: $('pubDetail').value, type: $('pubType').value, year: +$('pubYear').value, month: +$('pubMonth').value, indexing: $('pubIndexing').value, affiliation: $('pubAffiliation').value } }
function auditText(e) { const en = window.cocLanguage === 'en'; let verb = (en ? { create: 'Created', update: 'Edited', delete: 'Deleted', import: 'Imported', restore: 'Restored' } : { create: 'เพิ่ม', update: 'แก้ไข', delete: 'ลบ', import: 'นำเข้า', restore: 'คืนค่า' })[e.action] || e.action; let name = en ? (e.entity === 'program' ? 'program of ' + e.id : e.entity === 'publications' ? (Array.isArray(e.id) ? e.id.length : 1) + ' publications' : 'publication #' + e.id) : (e.entity === 'program' ? 'หลักสูตรของ ' + e.id : e.entity === 'publications' ? 'ผลงาน ' + (Array.isArray(e.id) ? e.id.length : 1) + ' รายการ' : 'ผลงาน #' + e.id); return `${new Date(e.time).toLocaleString(en ? 'en-US' : 'th-TH')} · ${verb} ${name}${e.restore_of ? (en ? ' (reverted entry #' : ' (ย้อนรายการ #') + e.restore_of + ')' : ''}` }
let auditPage = 1, auditTotal = 0;
async function showAudit() { let query = new URLSearchParams({ page: auditPage, action: $('auditAction').value, entity: $('auditEntity').value, start: $('auditStart').value, end: $('auditEnd').value, search: $('auditSearch').value }); const result = await api('/api/audit?' + query); auditTotal = result.total; $('auditCount').textContent = `พบ ${result.total} รายการ`; if (auditPage > 1 && !result.items.length) { auditPage--; return showAudit() } $('auditPage').textContent = `หน้า ${auditPage} / ${Math.max(1, Math.ceil(auditTotal / 25))}`; $('auditPrevious').disabled = auditPage <= 1; $('auditNext').disabled = auditPage * 25 >= auditTotal; $('auditList').innerHTML = result.items.length ? result.items.map(e => `<details class="record"><summary>${escapeHTML(auditText(e))}</summary><pre style="white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px;color:#52697e">${escapeHTML(JSON.stringify({ before: e.before, after: e.after }, null, 2))}</pre>${e.action !== 'restore' ? `<button class="quiet" data-restore="${e.seq}">คืนค่าการเปลี่ยนแปลงนี้</button>` : ''}</details>`).join('') : '<p class="muted">ไม่พบประวัติตามตัวกรอง</p>' }
function review(title, body, keyword = '') { return new Promise(resolve => { const d = $('reviewDialog'), input = $('reviewInput'), word = window.cocLanguage === 'en' && keyword === 'ลบ' ? 'DELETE' : keyword; $('reviewTitle').textContent = title; $('reviewBody').textContent = body; $('reviewPrompt').hidden = !keyword; input.hidden = !keyword; input.value = ''; $('reviewPrompt').textContent = window.cocLanguage === 'en' ? `Type ${word} to confirm` : `พิมพ์ ${word} เพื่อยืนยัน`; $('reviewAccept').disabled = !!keyword; input.oninput = () => { $('reviewAccept').disabled = input.value !== word }; d.showModal(); const done = answer => { d.close(); resolve(answer) }; $('reviewAccept').onclick = () => done(true); $('reviewCancel').onclick = () => done(false); d.oncancel = e => { e.preventDefault(); done(false) }; if (keyword) input.focus() }) }
$('pubForm').onsubmit = async e => { e.preventDefault(); const values = formValue(); if (editingId) { let before = data.find(x => x.id === editingId); let changes = Object.keys(values).filter(k => values[k] !== before[k]).map(k => `${k}: ${String(before[k]).slice(0, 110)} → ${String(values[k]).slice(0, 110)}`); if (!changes.length) { toast('ไม่มีข้อมูลที่เปลี่ยน'); return } if (!await review('ตรวจสอบก่อนบันทึก', changes.join('\n'))) return } try { let saved = await api(editingId ? `/api/publications/${editingId}` : '/api/publications', editingId ? 'PUT' : 'POST', values); clearForm(); await refresh(); if (saved.year < +$('from').value) $('from').value = String(saved.year); if (saved.year > +$('to').value) $('to').value = String(saved.year); render(); toast('บันทึกผลงานแล้ว') } catch (err) { toast(err.message, true) } };
$('pubCancel').onclick = clearForm;
$('records').addEventListener('click', async e => { const btn = e.target.closest('[data-edit],[data-delete]'); if (!btn) return; const id = +(btn.dataset.edit || btn.dataset.delete); if (btn.dataset.edit) fillForm(id); else { let row = data.find(x => x.id === id); if (!row || !await review('ยืนยันการลบผลงาน', `#${id} · ${row.staff}\n${row.detail.slice(0, 250)}`, 'ลบ')) return; try { await api(`/api/publications/${id}`, 'DELETE'); await refresh(); toast('ลบรายการแล้ว สามารถคืนค่าได้จากประวัติ') } catch (err) { toast(err.message, true) } } });
$('chart').addEventListener('click', e => { const point = e.target.closest('[data-year]'); if (!point) return; drillYear = +point.dataset.year; page = 0; render(); $('records').scrollIntoView({ behavior: 'smooth', block: 'start' }) });
$('clearYear').onclick = () => { drillYear = null; page = 0; render() };
$('auditToggle').onclick = async () => { $('auditPanel').hidden = !$('auditPanel').hidden; if (!$('auditPanel').hidden) try { await showAudit() } catch (err) { toast(err.message, true) } };
for (const id of ['auditAction', 'auditEntity', 'auditStart', 'auditEnd']) $(id).onchange = () => { auditPage = 1; showAudit().catch(err => toast(err.message, true)) }; $('auditSearch').oninput = () => { clearTimeout(showAudit.timer); showAudit.timer = setTimeout(() => { auditPage = 1; showAudit().catch(err => toast(err.message, true)) }, 250) }; $('auditPrevious').onclick = () => { auditPage--; showAudit().catch(err => toast(err.message, true)) }; $('auditNext').onclick = () => { auditPage++; showAudit().catch(err => toast(err.message, true)) }; $('auditList').onclick = async e => { let seq = +e.target.dataset.restore; if (!seq) return; if (!await review('คืนค่าการเปลี่ยนแปลง', `ย้อนรายการประวัติ #${seq} ข้อมูลปัจจุบันจะเปลี่ยน และมี log ใหม่บันทึกการคืนค่า`)) return; try { await api('/api/restore', 'POST', { seq }); mapping = await api('/api/programs'); await refresh(); await showAudit(); toast('คืนค่าแล้ว') } catch (err) { toast(err.message, true) } };
$('csvFile').onchange = async e => { const file = e.target.files[0]; if (!file) return; try { const res = await api('/api/import-preview', 'POST', file); candidates = res.candidates; $('importSummary').textContent = `${res.rows} แถว · เพิ่มใหม่ ${res.new} · มีแล้ว ${res.existing} · ข้อมูลไม่ถูกต้อง ${res.invalid}`; $('importConfirm').hidden = !res.new; $('importSample').textContent = `เพิ่มใหม่ (แสดง ${res.preview.length} รายการแรก)\n${res.preview.map(x => `${x.year} · ${x.staff} · ${x.detail.slice(0, 120)}`).join('\n') || 'ไม่มี'}\n\nมีแล้ว (แสดง ${res.existing_preview.length} รายการแรก)\n${res.existing_preview.map(x => `แถว ${x.row} · ${x.staff} · ${x.detail}`).join('\n') || 'ไม่มี'}\n\nข้อมูลไม่ถูกต้อง (แสดง ${res.invalid_preview.length} รายการแรก)\n${res.invalid_preview.map(x => `แถว ${x.row} · ${x.staff} · ${x.detail}`).join('\n') || 'ไม่มี'}` } catch (err) { toast(err.message, true) } finally { e.target.value = '' } };
$('importConfirm').onclick = async () => { if (!confirm(window.cocLanguage === 'en' ? `Import ${candidates.length} new publications?` : `เพิ่มผลงานใหม่ ${candidates.length} รายการ?`)) return; try { let res = await api('/api/import', 'POST', { candidates }); candidates = []; $('importConfirm').hidden = true; $('importSummary').textContent = `นำเข้าแล้ว ${res.added} รายการ`; $('importSample').textContent = ''; await refresh(); toast('นำเข้าข้อมูลแล้ว') } catch (err) { toast(err.message, true) } };
clearForm();
